# Generated by Django 5.1.5 on 2025-01-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_trainer_bio_alter_trainer_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
