# Generated by Django 5.1.5 on 2025-01-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0003_alter_trainer_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('trainers', models.ManyToManyField(limit_choices_to={'role': 'trainer'}, related_name='courses', to='trainers.trainer')),
            ],
        ),
    ]
