# Generated by Django 5.1.5 on 2025-01-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_delete_payment'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainer',
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(limit_choices_to={'role': 'trainer'}, related_name='courses', to='trainers.trainer'),
        ),
    ]
